apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devguru-group-binding
  namespace: projectx
subjects:
- kind: Group
  name: gurus
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: devguru
  apiGroup: rbac.authorization.k8s.io


