apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devguru
  namespace: projectx
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs: ["*"]


