Vagrant.configure("2") do |config|

    config.vm.define "kub2" do |kub2|
        #kub2.vm.box="shekeriev/almalinux-9.6"
		kub2.vm.box="AL9BOX1"
        kub2.vm.hostname = "kub2.lab1"
        kub2.vm.network "private_network", ip: "192.168.99.100"
		kub2.vm.network "forwarded_port", guest: 30001, host: 8888, auto_correct: true
        kub2.vm.provision "shell", path: "docker-minikube-setup.sh"
        kub2.vm.provider :virtualbox do |vb|
			vb.gui = true
            vb.customize ["modifyvm", :id, "--memory", "6144"]
			vb.customize ["modifyvm", :id, "--cpus", "6"]
      end
		kub2.vm.synced_folder "manifests", "/home/vagrant/manifests/"
    end  
end 

