# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "node1" do |node1|
    node1.vm.box = "KubImage"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.100.101"
	#node1.vm.synced_folder "./Homework", "/home/strahil/homework", create: true
	node1.vm.provision "shell", path: "add_hosts.sh"
	node1.vm.provision "shell", path: "cluster_add.sh"
	node1.vm.provision "shell", inline: <<EOS
		apt-get update -y && apt-get install -y nfs-common
EOS
	node1.vm.provider :virtualbox do |vb|
		vb.gui = true
        vb.customize ["modifyvm", :id, "--memory", "2048"]
		vb.customize ["modifyvm", :id, "--cpus", "2"]
	end
  end
  
  config.vm.define "node2" do |node2|
    node2.vm.box = "KubImage"
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "192.168.100.102"
	node2.vm.provision "shell", path: "add_hosts.sh"
	node2.vm.provision "shell", inline: <<EOS
		/bin/bash /vagrant/join.sh
		sleep 2
		apt-get update -y && apt-get install -y nfs-common
EOS
	node2.vm.provider :virtualbox do |vb|
		vb.gui = true
		vb.customize ["modifyvm", :id, "--memory", "2048"]
		vb.customize ["modifyvm", :id, "--cpus", "2"]
	end
  end

  config.vm.define "node3" do |node3|
    node3.vm.box = "KubImage"
    node3.vm.hostname = "node3"
    node3.vm.network "private_network", ip: "192.168.100.103"
	node3.vm.provision "shell", path: "add_hosts.sh"
	node3.vm.provision "shell", inline: <<EOS
		/bin/bash /vagrant/join.sh
		sleep 2
		apt-get update -y && apt-get install -y nfs-common
EOS
	node3.vm.provider :virtualbox do |vb|
		vb.gui = true
		vb.customize ["modifyvm", :id, "--memory", "2048"]
		vb.customize ["modifyvm", :id, "--cpus", "2"]
	end
  end
  
  config.vm.define "nfs" do |nfs|
    nfs.vm.box = "shekeriev/debian-12.11"
    nfs.vm.hostname = "nfs"
    nfs.vm.network "private_network", ip: "192.168.100.104"
	nfs.vm.provision "shell", path: "add_hosts.sh"
	nfs.vm.provision "shell", path: "nfs_setup.sh"
	nfs.vm.provider :virtualbox do |vb|
		vb.gui = true
		vb.customize ["modifyvm", :id, "--memory", "1024"]
		vb.customize ["modifyvm", :id, "--cpus", "1"]
	end
  end

end

