apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: projectx
  labels:
    app: fun-facts
    role: producer
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: fun-facts
    role: producer


