Vagrant.configure("2") do |config|

    config.vm.define "kub3" do |kub3|
        #kub3.vm.box="shekeriev/almalinux-9.6"
		kub3.vm.box="AL9BOX1"
        kub3.vm.hostname = "kub3.lab1"
        kub3.vm.network "private_network", ip: "192.168.99.100"
		kub3.vm.network "forwarded_port", guest: 30001, host: 8888, auto_correct: true
        kub3.vm.provision "shell", path: "docker-kind-setup.sh"
        kub3.vm.provider :virtualbox do |vb|
			vb.gui = true
            vb.customize ["modifyvm", :id, "--memory", "6144"]
			vb.customize ["modifyvm", :id, "--cpus", "6"]
      end
		kub3.vm.synced_folder "manifests", "/home/vagrant/manifests/"
    end  
end 

